name: nightly

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: passsy/flutterw:base-0.4.1

    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          mkdir -p /flutter
          git clone https://github.com/flutter/flutter.git -b stable /flutter
          echo "/flutter/bin" >> $GITHUB_PATH
      - run: |
          cd test
          dart pub get
      - run: |
          cd test
          dart run test